/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 brazillian_boot_-_vento_tita.glb 
Author: Akaize (https://sketchfab.com/Akaize)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/brazillian-boot-vento-tita-6e95243a64a545aab3af43173f6b3e04
Title: Brazillian Boot - Vento Titã
*/

import React, { useRef } from "react";
import { ContactShadows, useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { useControls } from "leva";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/Boot/brazillian_boot_-_vento_tita.glb"
  );
  const { viewport } = useThree();
  const ref = useRef();

  useFrame(() => {
    // ref.current.rotation.x += 0.02;
    // ref.current.rotation.y += 0.02;
  });

  // const materialProps = useControls({
  //   thickness: { value: 0.2, min: 0, max: 3, step: 0.05 },
  //   roughness: { value: 0, min: 0, max: 1, step: 0.1 },
  //   transmission: { value: 1, min: 0, max: 1, step: 0.1 },
  //   ior: { value: 1.2, min: 0, max: 3, step: 0.1 },
  //   chromaticAberration: { value: 0.02, min: 0, max: 1 },
  //   backside: { value: true },
  // });

  return (
    <group scale={viewport.width / 10} {...props} dispose={null}>
      <group
        ref={ref}
        position={[-0.16, -0.5, -0.22]}
        rotation={[0, -Math.PI / 2, 0]}
      >
        <group>
          <group scale={[1.003, 1, 1]}>
            <mesh
              castShadow
              geometry={nodes.Object_8.geometry}
              material={materials.Palmilha_Tecido}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials.Palmilha_Base}
            />
          </group>
          <group scale={[1.003, 1, 1]}>
            <mesh
              castShadow
              geometry={nodes.Object_13.geometry}
              material={materials.Polimero_Cano}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_14.geometry}
              material={materials.Polimero_Cano_Forro}
            />
          </group>
          <group scale={[1.003, 1, 1]}>
            <mesh
              castShadow
              geometry={nodes.Object_18.geometry}
              material={materials.Nanox_Marrom}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_19.geometry}
              material={materials.Nanox_Borda}
            />
          </group>
          <group scale={[1.003, 1, 1]}>
            <mesh
              castShadow
              geometry={nodes.Object_21.geometry}
              material={materials.Nanox_Marrom}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_22.geometry}
              material={materials.Nanox_Borda}
            />
          </group>
          <group
            position={[0.593, 0.638, -0.708]}
            rotation={[-0.671, -0.143, -1.425]}
            scale={0.979}
          >
            <mesh
              castShadow
              geometry={nodes.Object_24.geometry}
              material={materials.Ilhos_Pino}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_25.geometry}
              material={materials.Ilhos}
            />
          </group>
          <group
            position={[-0.492, 0.694, -0.847]}
            rotation={[-0.587, 0.089, 1.362]}
            scale={0.979}
          >
            <mesh
              castShadow
              geometry={nodes.Object_27.geometry}
              material={materials.Ilhos_Pino}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_28.geometry}
              material={materials.Ilhos}
            />
          </group>
          <group
            position={[0.586, 1.166, -0.837]}
            rotation={[-0.387, 0.021, -1.673]}
          >
            <mesh
              castShadow
              geometry={nodes.Object_30.geometry}
              material={materials.Ilhos_Pino}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_31.geometry}
              material={materials.Ilhos}
            />
          </group>
          <group
            position={[0.681, 1.559, -0.921]}
            rotation={[-0.389, -0.115, -1.751]}
          >
            <mesh
              castShadow
              geometry={nodes.Object_33.geometry}
              material={materials.Ilhos_Pino}
            />
            <mesh
              castShadow
              geometry={nodes.Object_34.geometry}
              material={materials.Ilhos}
            />
          </group>
          <group
            position={[-0.55, 1.608, -1.077]}
            rotation={[-0.433, 0.092, 1.58]}
          >
            <mesh
              castShadow
              geometry={nodes.Object_36.geometry}
              material={materials.Ilhos_Pino}
            />
            <mesh
              castShadow
              geometry={nodes.Object_37.geometry}
              material={materials.Ilhos}
            />
          </group>
          <group
            position={[-0.47, 1.179, -0.976]}
            rotation={[-0.519, 0.005, 1.598]}
          >
            <mesh
              castShadow
              geometry={nodes.Object_39.geometry}
              material={materials.Ilhos_Pino}
            />
            <mesh
              castShadow
              geometry={nodes.Object_40.geometry}
              material={materials.Ilhos}
            />
          </group>
          <group position={[0, -0.002, 0.001]} scale={[1.003, 1, 1]}>
            <mesh
              castShadow
              geometry={nodes.Object_64.geometry}
              material={materials.Nanox_Preto}
            />
            <mesh
              castShadow
              geometry={nodes.Object_65.geometry}
              material={materials.Nanox_Borda}
            />
          </group>
          <mesh
            castShadow
            geometry={nodes.Object_4.geometry}
            material={materials.Sola}
          />
          <mesh
            castShadow
            geometry={nodes.Object_5.geometry}
            material={materials.Sola}
          />
          <mesh
            castShadow
            geometry={nodes.Object_6.geometry}
            material={materials.Sola}
          />
          <mesh
            castShadow
            geometry={nodes.Object_11.geometry}
            material={materials.Forro}
            scale={[1.003, 1, 1]}
          />
          <mesh
            castShadow
            geometry={nodes.Object_16.geometry}
            material={materials.Polimero_Cano}
            scale={[1.003, 1, 1]}
          />
          <mesh
            castShadow
            geometry={nodes.Object_42.geometry}
            material={materials.Ilhos}
            position={[0.204, 0.254, 0.868]}
            rotation={[-2.216, -1.181, -2.383]}
            scale={0.879}
          />
          <mesh
            castShadow
            geometry={nodes.Object_44.geometry}
            material={materials.Ilhos}
            position={[0.335, 0.269, 0.66]}
            rotation={[-1.87, -1.134, -2.497]}
            scale={0.879}
          />
          <mesh
            castShadow
            geometry={nodes.Object_46.geometry}
            material={materials.Ilhos}
            position={[0.438, 0.346, 0.434]}
            rotation={[-1.863, -0.976, -2.17]}
            scale={0.879}
          />
          <mesh
            castShadow
            geometry={nodes.Object_48.geometry}
            material={materials.Ilhos}
            position={[0.543, 0.427, 0.101]}
            rotation={[-1.221, -0.8, -1.658]}
            scale={0.879}
          />
          <mesh
            castShadow
            geometry={nodes.Object_50.geometry}
            material={materials.Ilhos}
            position={[0.559, 0.531, -0.181]}
            rotation={[-1.191, -0.618, -1.617]}
            scale={0.879}
          />
          <mesh
            castShadow
            geometry={nodes.Object_52.geometry}
            material={materials.Ilhos}
            position={[-0.283, 0.266, 0.88]}
            rotation={[-2.102, 1.253, 2.312]}
            scale={0.879}
          />
          <mesh
            castShadow
            geometry={nodes.Object_54.geometry}
            material={materials.Ilhos}
            position={[-0.336, 0.322, 0.61]}
            rotation={[-1.794, 1.172, 2.348]}
            scale={0.879}
          />
          <mesh
            castShadow
            geometry={nodes.Object_56.geometry}
            material={materials.Ilhos}
            position={[-0.412, 0.422, 0.33]}
            rotation={[-1.31, 1.014, 1.813]}
            scale={0.879}
          />
          <mesh
            castShadow
            geometry={nodes.Object_58.geometry}
            material={materials.Ilhos}
            position={[-0.487, 0.514, 0.006]}
            rotation={[-1.294, 0.756, 1.741]}
            scale={0.879}
          />
          <mesh
            castShadow
            geometry={nodes.Object_60.geometry}
            material={materials.Ilhos}
            position={[-0.512, 0.608, -0.288]}
            rotation={[-1.219, 0.581, 1.597]}
            scale={0.879}
          />
          <mesh
            castShadow
            geometry={nodes.Object_62.geometry}
            material={materials.Borracha_Lateral}
          />
          <mesh
            castShadow
            geometry={nodes.Object_67.geometry}
            material={materials.Sobre_Biqueira}
            scale={[1.003, 1, 1]}
          />
          <mesh
            castShadow
            geometry={nodes.Object_69.geometry}
            material={materials.Costura_Marrom}
          />
          <mesh
            castShadow
            geometry={nodes.Object_71.geometry}
            material={materials.Costura_Marrom}
          />
          <mesh
            castShadow
            geometry={nodes.Object_73.geometry}
            material={materials.Costura_Marrom}
          />
          <mesh
            castShadow
            geometry={nodes.Object_75.geometry}
            material={materials.Costura_Marrom}
          />
          <mesh
            castShadow
            geometry={nodes.Object_77.geometry}
            material={materials.Costura_Cinza}
          />
          <mesh
            castShadow
            geometry={nodes.Object_78.geometry}
            material={materials.Costura_Cinza}
          />
          <mesh
            castShadow
            geometry={nodes.Object_80.geometry}
            material={materials.Costura_Cinza}
          />
          <mesh
            castShadow
            geometry={nodes.Object_82.geometry}
            material={materials.Costura_Cinza}
          />
          <mesh
            castShadow
            geometry={nodes.Object_84.geometry}
            material={materials.Costura_Cinza}
          />
          <mesh
            castShadow
            geometry={nodes.Object_85.geometry}
            material={materials.Costura_Cinza}
          />
          <mesh
            castShadow
            geometry={nodes.Object_87.geometry}
            material={materials.Cadaro}
          />
          <mesh
            castShadow
            geometry={nodes.Object_89.geometry}
            material={materials.CA_42454}
          />
          <mesh
            castShadow
            geometry={nodes.Object_91.geometry}
            material={materials.Pano_Traz}
          />
          <mesh
            castShadow
            geometry={nodes.Object_93.geometry}
            material={materials.CLIMATEX}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Boot/brazillian_boot_-_vento_tita.glb");
